name: SecureThread CI - Enhanced Security Scan
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      ### BACKEND - PYTHON SECURITY (Bandit)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan on Backend
        run: |
          cd Backend
          bandit -r . -c bandit.yaml

      ### FRONTEND - JS SECURITY (ESLint)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install ESLint
        run: |
          cd Frontend
          npm install eslint
          npx eslint . || true  # continue even if errors

      ### REPOSITORY SCANNER TESTING
      - name: Test Repository Scanner
        run: |
          cd Backend
          pip install -r requirements.txt
          python -c "
          from repo_scanner import GitHubRepoScanner
          scanner = GitHubRepoScanner()
          print('✅ Repository scanner imports successfully')
          "

      - name: Finish Job
        run: echo "✅ Enhanced Security CI Completed"
